name: CMake Build Matrix

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] #
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: gcc
          - os: macos-latest
            compiler: clang
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Install Ninja
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            choco install ninja
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get install -y ninja-build
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install ninja
          fi

      - name: Cache vcpkg
        uses: actions/cache@v4.0.2
        with:
          path: |
            vcpkg
            vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: vcpkg installation
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./bootstrap-vcpkg.bat
          else
            ./bootstrap-vcpkg.sh
          fi
          ./vcpkg integrate install
          ./vcpkg install

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: |
          cmake --build build --config Release
