name: CMake Build Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: gcc
          - os: macos-latest
            compiler: clang
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

#      - name: Set up cache
#        id: cache-cpm
#        uses: actions/cache@v4.0.2
#        with:
#          path: ~/cpm-cache
#          key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
#          restore-keys: |
#            ${{ runner.os }}-cpm-

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
# cmake -B build -DCMAKE_BUILD_TYPE=Release -DCPM_SOURCE_CACHE=~/cpm-cache

      - name: Build
        run: |
          cmake --build build --config Release
