name: CMake Build Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ] #, ubuntu-latest, macos-latest
        include:
          - os: windows-latest
            compiler: msvc
#          - os: ubuntu-latest
#            compiler: gcc
#          - os: macos-latest
#            compiler: clang
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: false

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
      # cmake -B build -DCMAKE_BUILD_TYPE=Release -DCPM_SOURCE_CACHE=~/cpm-cache

      - name: Build
        run: |
          cmake --build build --config Release
