name: CMake Build Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: gcc
          - os: macos-latest
            compiler: clang
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - uses: lukka/get-cmake@latest

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-vcpkg@v11.5
        with:
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
          buildPreset: 'ninja-multi-vcpkg'
          buildPresetAdditionalArgs: "['--config Release']"
          testPreset: 'ninja-multi-vcpkg'
          testPresetAdditionalArgs: "['--config Release']"

#      - name: run-vcpkg
#        uses: lukka/run-vcpkg@v11.5
#        with:
#          vcpkg-dir: '${{ runner.workspace }}/vcpkg'
#          # vcpkg-triplet: x64-windows
#          appendedCacheKey: ${{hashFiles('vcpkg.json')}}

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: |
          cmake --build build --config Release
