name: CMake Build Matrix

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: clang-latest # gcc-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: vcpkg installation
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./bootstrap-vcpkg.bat
          else
            ./bootstrap-vcpkg.sh
          fi
          ./vcpkg integrate install
          ./vcpkg install

      - name: Cache vcpkg packages
        uses: actions/cache@v4.0.2
        with:
          path: |
            ${{ github.workspace }}/vcpkg/installed
            ${{ github.workspace }}/vcpkg/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: |
          cmake --build build --config Release

      - name: List contents of output directory
        run: |
          echo "Contents of output directory:"
          ls -R ${{ github.workspace }}/output/bin/release


#      - name: Run tests
#        run: |
#          ctest --test-dir ${{ github.workspace }}/output/bin/release --output-on-failure -C Release